import { AppRoute } from '../../types';
import { TourChapter } from './types';

export const chapter5: TourChapter = {
  id: 5,
  title: 'Laboratorios y fotos de progreso',
  steps: [
    {
      id: 'ch5-go-to-labs-tab',
      route: AppRoute.PATIENT_DETAIL,
      tab: 'menus',
      target: '[data-tour="patient-tab-labs"]',
      autoNavigate: true,
      placement: 'bottom',
      title: 'Vamos a Laboratorios',
      body: 'Haz clic en la pestaña "Laboratorios".',
      advanceOn: { type: 'click' },
    },
    {
      id: 'ch5-upload-lab',
      route: AppRoute.PATIENT_DETAIL,
      tab: 'labs',
      target: '[data-tour="patient-labs-upload"]',
      placement: 'top',
      title: 'Sube un archivo de laboratorio',
      body: 'Haz clic en "Subir" para cargar un resultado de laboratorio (PDF o imagen) de tu paciente. Cuando termines, haz clic en Siguiente.',
      advanceOn: { type: 'manual' },
    },
    {
      id: 'ch5-lab-interpretation',
      route: AppRoute.PATIENT_DETAIL,
      tab: 'labs',
      target: '[data-tour="patient-labs-interpretation"]',
      placement: 'top',
      title: 'Interpretación de laboratorios',
      body: 'Aquí, al hacer clic en cada documento subido, puedes agregar notas de interpretación clínica de ese laboratorio — información que te ayuda a tomar decisiones para el plan nutricional de tu paciente.',
      advanceOn: { type: 'manual' },
    },
    {
      id: 'ch5-go-to-photos-tab',
      route: AppRoute.PATIENT_DETAIL,
      tab: 'labs',
      target: '[data-tour="patient-tab-photos"]',
      placement: 'bottom',
      title: 'Ahora vamos a Fotos',
      body: 'Haz clic en la pestaña "Fotos".',
      advanceOn: { type: 'click' },
    },
    {
      id: 'ch5-upload-photo',
      route: AppRoute.PATIENT_DETAIL,
      tab: 'photos',
      target: '[data-tour="patient-photos-gallery"]',
      placement: 'top',
      title: 'Sube una foto de progreso',
      body: 'Haz clic en "Subir" para cargar una foto de progreso de tu paciente.',
      advanceOn: { type: 'manual' },
    },
    {
      id: 'ch5-photo-preview',
      route: AppRoute.PATIENT_DETAIL,
      tab: 'photos',
      target: '[data-tour="patient-photos-gallery"]',
      placement: 'top',
      title: 'Aquí aparece la foto subida',
      body: 'La foto que subiste ya está en esta galería, ordenada por fecha. Cuando termines de revisarla, haz clic en Siguiente.',
      advanceOn: { type: 'manual' },
    },
  ],
};
