import { AppRoute } from '../../types';
import { TourChapter } from './types';

export const chapter6: TourChapter = {
  id: 6,
  title: 'Configuración del paciente',
  steps: [
    {
      id: 'ch6-go-to-config-tab',
      route: AppRoute.PATIENT_DETAIL,
      tab: 'photos',
      target: '[data-tour="patient-tab-config"]',
      autoNavigate: true,
      placement: 'bottom',
      title: 'Vamos a Configuración',
      body: 'Haz clic en la pestaña "Config.".',
      advanceOn: { type: 'click' },
    },
    {
      id: 'ch6-export-profile',
      route: AppRoute.PATIENT_DETAIL,
      tab: 'config',
      target: '[data-tour="patient-config-export"]',
      placement: 'top',
      title: 'Exporta el perfil completo',
      body: 'Desde aquí puedes exportar toda la información que has ingresado de tu paciente en un archivo .doc: datos clínicos y el contenido completo de cada evaluación.',
      advanceOn: { type: 'manual' },
    },
    {
      id: 'ch6-export-profile-click',
      route: AppRoute.PATIENT_DETAIL,
      tab: 'config',
      target: '[data-tour="patient-config-export-profile-btn"]',
      placement: 'top',
      title: 'Haz clic para ver las opciones',
      body: 'Haz clic en "Exportar Perfil Completo en .doc".',
      advanceOn: { type: 'click' },
    },
    {
      id: 'ch6-export-all',
      route: AppRoute.PATIENT_DETAIL,
      tab: 'config',
      target: '[data-tour="patient-config-export-modal"]',
      placement: 'right',
      title: 'Exportar todo',
      body: 'Con "Exportar Todo (.zip)" descargas un reporte completo del paciente, incluyendo los menús en PDF. También puedes exportar solo la información clínica, o la evaluación y menú de una fecha específica. Puedes probarlo si quieres, o solo haz clic en Siguiente para continuar.',
      advanceOn: { type: 'manual' },
    },
    {
      id: 'ch6-raw-data',
      route: AppRoute.PATIENT_DETAIL,
      tab: 'config',
      target: '[data-tour="patient-config-raw-data"]',
      placement: 'top',
      title: 'Exportar / importar datos crudos',
      body: 'Aquí puedes descargar toda la información de este paciente en formato JSON, o importar un JSON previamente exportado para actualizar sus datos en el sistema.',
      advanceOn: { type: 'manual' },
    },
    {
      id: 'ch6-delete-patient',
      route: AppRoute.PATIENT_DETAIL,
      tab: 'config',
      target: '[data-tour="patient-config-delete"]',
      placement: 'top',
      title: 'Eliminar paciente',
      body: 'Y aquí podrías eliminar permanentemente a este paciente y todos sus registros. No lo probaremos ahora para no borrar tu paciente de prueba — solo queremos que sepas dónde encontrarlo el día que lo necesites.',
      advanceOn: { type: 'manual' },
    },
  ],
};
